version: '2.1'

services:
  docker-nginx:
    image: nginx:1.12.0
    restart: unless-stopped
    network_mode: host
    build: ./
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/www.qiangfeng.co.uk/fullchain.pem:/www.qiangfeng.co.uk/fullchain.pem
      - /etc/letsencrypt/live/www.qiangfeng.co.uk/privkey.pem:/www.qiangfeng.co.uk/privkey.pem
      - /etc/letsencrypt/live/seedbox.qiangfeng.co.uk/fullchain.pem:/seedbox.qiangfeng.co.uk/fullchain.pem
      - /etc/letsencrypt/live/seedbox.qiangfeng.co.uk/privkey.pem:/seedbox.qiangfeng.co.uk/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/dhparam.pem
    ports:
      - 80:80
      - 443:443
      - 8000:8000
